server :
  port : 8080
  servlet:
    encoding :
      charset: UTF-8
      enabled: true
      force : true
  shutdown: graceful
  tomcat:
    connection-timeout: 90s
    max-connections: 50
  error :
    include-message: always
    include-stacktrace: never
    include-binding-errors: always
    whitelabel:
      enabled: false


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mini_commerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: MINI_COMMERCE_USER
    password: MINICOMMERCEUSER
  hikari:
    maximum-pool-size: 10
    connection-timeout: 60000
    max-lifetime: 25200000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   # 필요에 따라 none, validate, update, create, create-drop 중 선택
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: user
      password: 1234


logging:
  level:
    root: info
    org.hibernate.SQL: debug           # 실행되는 SQL 로그
    org.hibernate.type.descriptor.sql: trace # 바인딩 파라미터 값 출력
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: warn
    lims.api: debug
  file:
    path: C:\dev\jpa-log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        clean-history-on-start: false


jwt:
  expiration_time: 86400000
  secret: RElBUllfQU5EX0NPTU1VTklUWV9QUk9KRUNUX0RBV05BUllfQURNSU5fU0VDUkVUX0tFWQ==


